import type { Job } from './types'

const daysAgo = (days: number): string => new Date(Date.now() - days * 86400000).toISOString()

export const SAMPLE_JOBS: Job[] = [
  {
    id: 'job_1',
    title: 'Data analyst (part-time)',
    company: 'Figma',
    location: 'Homs',
    mode: 'Hybrid',
    type: 'Part time',
    posted_at: daysAgo(7),
    about: [
      'Three days a week, helping the operations team answer its own questions.',
      'You will write SQL against a warehouse that is mostly tidy, build the weekly numbers, and say plainly when the data cannot answer what was asked. Homs office, two days from home.',
    ],
    years: '2+ years total experience',
    skills: [
      { name: 'Data Analysis', level: 'Required' },
      { name: 'SQL', level: 'Required' },
      { name: 'Python', level: 'Preferred' },
      { name: 'Pandas', level: 'Optional' },
    ],
    languages: [{ name: 'English', level: 'Advanced or better' }],
    questions: [
      { text: 'Do you have the right to work in Syria?', kind: 'Yes or no', required: true },
      { text: 'When could you start?', kind: 'Short answer', required: true },
    ],
  },
  {
    id: 'job_2',
    title: 'Data platform engineer',
    company: 'Airbnb',
    location: 'Damascus',
    mode: 'On-site',
    type: 'Full time',
    posted_at: daysAgo(19),
    about: [
      'You will own the data behind the network: the schema, the checks that catch a bad record the week it lands, and the reports the regulator reads.',
      'Telecom experience is welcome but not the only way in — somebody who has been rigorous with somebody else’s messy data will do well here.',
    ],
    years: '3+ years total experience',
    skills: [
      { name: 'Data Analysis', level: 'Required' },
      { name: 'SQL', level: 'Required' },
    ],
    languages: [
      { name: 'Arabic', level: 'Native' },
      { name: 'English', level: 'Fluent or better' },
    ],
    questions: [{ text: 'Have you worked with network telemetry or billing data before?', kind: 'Yes or no', required: false }],
  },
  {
    id: 'job_3',
    title: 'Senior backend engineer',
    company: 'Google',
    location: 'Damascus',
    mode: 'On-site',
    type: 'Full time',
    posted_at: daysAgo(30),
    about: [
      'The service behind the matching engine, and the people who keep it standing.',
      'You would join four engineers in Damascus and one in Amman.',
      'On-call is one week in four, and quiet.',
    ],
    years: '5+ years total experience',
    skills: [
      { name: 'Python', level: 'Required' },
      { name: 'PostgreSQL', level: 'Required' },
      { name: 'Docker', level: 'Preferred' },
      { name: 'FastAPI', level: 'Preferred' },
      { name: 'Kubernetes', level: 'Optional' },
    ],
    languages: [
      { name: 'Arabic', level: 'Native' },
      { name: 'English', level: 'Advanced or better' },
    ],
    questions: [
      { text: 'Do you have the right to work in Syria?', kind: 'Yes or no', required: true },
      { text: 'Are you willing to join an on-call rota?', kind: 'Yes or no', required: false },
      { text: 'When could you start?', kind: 'Short answer', required: true },
    ],
  },
  {
    id: 'job_4',
    title: 'DevOps engineer (contract)',
    company: 'Stripe',
    location: 'Anywhere, remote',
    mode: 'Remote',
    type: 'Contract',
    posted_at: daysAgo(23),
    about: [
      'Six months, with a view to longer, rebuilding a deployment pipeline that has grown by accident.',
      'You will be the only person doing this work, so it suits somebody who is comfortable deciding and then living with the decision.',
    ],
    years: '4+ years total experience',
    skills: [
      { name: 'Kubernetes', level: 'Required' },
      { name: 'Terraform', level: 'Required' },
      { name: 'AWS', level: 'Preferred' },
      { name: 'Go', level: 'Optional' },
    ],
    languages: [{ name: 'English', level: 'Fluent or better' }],
    questions: [{ text: 'What is your day rate?', kind: 'Short answer', required: true }],
  },
  {
    id: 'job_5',
    title: 'Frontend engineer (React)',
    company: 'Meta',
    location: 'Aleppo',
    mode: 'Hybrid',
    type: 'Full time',
    posted_at: daysAgo(34),
    about: [
      'The interface people actually use, and the small decisions that make it feel considered.',
      'You will work next to a designer rather than after one. Aleppo office, three days a week.',
    ],
    years: '3+ years total experience',
    skills: [
      { name: 'React', level: 'Required' },
      { name: 'TypeScript', level: 'Required' },
      { name: 'CSS', level: 'Preferred' },
      { name: 'Testing', level: 'Optional' },
    ],
    languages: [
      { name: 'Arabic', level: 'Native' },
      { name: 'English', level: 'Advanced or better' },
    ],
    questions: [{ text: 'Do you have the right to work in Syria?', kind: 'Yes or no', required: true }],
  },
  {
    id: 'job_6',
    title: 'Product designer',
    company: 'Spotify',
    location: 'Homs',
    mode: 'Remote',
    type: 'Full time',
    posted_at: daysAgo(9),
    about: [
      'One designer, one product, and the room to say what it should be.',
      'You will take a problem from a conversation to something shipped, and you will be the person who decides what it looks like when it gets there.',
    ],
    years: '4+ years total experience',
    skills: [
      { name: 'Figma', level: 'Required' },
      { name: 'Prototyping', level: 'Required' },
      { name: 'Design Systems', level: 'Preferred' },
      { name: 'Motion', level: 'Optional' },
    ],
    languages: [{ name: 'English', level: 'Fluent or better' }],
    questions: [{ text: 'Do you have a portfolio we can look at?', kind: 'Short answer', required: true }],
  },
]
